name: youtube
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_riverpod: ^1.0.4
  miniplayer: ^1.0.0+2
  timeago: ^3.0.2
  video_player: ^2.4.7
  get:
  line_icons: ^2.0.1
  flutter_svg: ^1.1.5
  animate_do: ^2.1.0
  badges:
  bubble: ^1.2.1
  logger: ^1.1.0
  provider: ^6.0.4
  webview_flutter: ^3.0.4
  http: ^0.13.5
  chewie: ^1.3.5
  freezed_annotation: ^2.0.3
  cached_network_image: ^3.2.1
  visibility_detector: ^0.2.2
  inview_notifier_list: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - json/